export function MockBowlsOk(): Promise<Response> {
  const mockResponse: Response = {
    ok: true,
    json: async () => (convertedBowlGames), //JSON.parse(JSON.stringify(convertedBowlGames)),
    headers: undefined,
    redirected: false,
    status: 0,
    statusText: '',
    type: 'basic',
    url: '',
    clone: function (): Response {
      throw new Error('Function not implemented.')
    },
    body: undefined,
    bodyUsed: false,
    arrayBuffer: function (): Promise<ArrayBuffer> {
      throw new Error('Function not implemented.')
    },
    blob: function (): Promise<Blob> {
      throw new Error('Function not implemented.')
    },
    formData: function (): Promise<FormData> {
      throw new Error('Function not implemented.')
    },
    text: function (): Promise<string> {
      throw new Error('Function not implemented.')
    },
  }
  return new Promise(resolve => resolve(mockResponse))
}



const BowlGames = [
  {
    "game": 1,
    "home": "Central Michigan",
    "ho": "CMIC",
    "visitor": "San Diego State",
    "vis": "SDST",
    "favorite": 1,
    "line": "3.5",
    "start": "12/21/2021 12:00:00",
    "note": "",
    "winner": "0",
    "priority": 0
  },
  {
    "game": 2,
    "home": "Oklahoma State",
    "ho": "OKST",
    "visitor": "Baylor",
    "vis": "BU",
    "favorite": 1,
    "line": "5.5",
    "start": "12/4/2021 5:00:00 PM",
    "note": "",
    "winner": "0",
    "priority": 0
  },
  {
    "game": 3,
    "home": "Northern Illinois",
    "ho": "NILL",
    "visitor": "Kent State",
    "vis": "KENT",
    "favorite": 0,
    "line": "2.5",
    "start": "12/4/2021 5:00:00 PM",
    "note": "",
    "winner": "0",
    "priority": 0
  },
  {
    "game": 4,
    "home": "San Diego State",
    "ho": "SDST",
    "visitor": "Utah State",
    "vis": "UTST",
    "favorite": 1,
    "line": "6.5",
    "start": "12/4/2021 5:00:00 PM",
    "note": "",
    "winner": "0",
    "priority": 0
  },
  {
    "game": 5,
    "home": "Louisiana Lafayette",
    "ho": "LALA",
    "visitor": "Appalachian State",
    "vis": "APST",
    "favorite": 0,
    "line": "3.5",
    "start": "12/4/2021 5:00:00 PM",
    "note": "",
    "winner": "0",
    "priority": 0
  },
  {
    "game": 6,
    "home": "Houston",
    "ho": "HOU",
    "visitor": "Cincinnati",
    "vis": "CIN",
    "favorite": 0,
    "line": "10.5",
    "start": "12/4/2021 5:00:00 PM",
    "note": "",
    "winner": "0",
    "priority": 0
  },
  {
    "game": 7,
    "home": "Georgia",
    "ho": "UGA",
    "visitor": "Alabama",
    "vis": "BAMA",
    "favorite": 1,
    "line": "6.5",
    "start": "12/4/2021 5:00:00 PM",
    "note": "",
    "winner": "0",
    "priority": 0
  },
  {
    "game": 8,
    "home": "Wake Forest",
    "ho": "WAKE",
    "visitor": "Pittsburgh",
    "vis": "PITT",
    "favorite": 1,
    "line": "3.5",
    "start": "12/4/2021 5:00:00 PM",
    "note": "",
    "winner": "0",
    "priority": 0
  },
  {
    "game": 9,
    "home": "Michigan",
    "ho": "MICH",
    "visitor": "Iowa",
    "vis": "IOWA",
    "favorite": 1,
    "line": "10.5",
    "start": "12/4/2021 5:00:00 PM",
    "note": "",
    "winner": "0",
    "priority": 0
  },
  {
    "game": 10,
    "home": "California",
    "ho": "CAL",
    "visitor": "Southern California",
    "vis": "USC",
    "favorite": 1,
    "line": "3.5",
    "start": "12/4/2021 5:00:00 PM",
    "note": "",
    "winner": "0",
    "priority": 0
  },
  {
    "game": 11,
    "home": "Western Kentucky",
    "ho": "WKEN",
    "visitor": "Texas San Antonio",
    "vis": "UTSA",
    "favorite": 1,
    "line": "1.5",
    "start": "12/4/2021",
    "note": "",
    "winner": "0",
    "priority": 0
  },
  {
    "game": 12,
    "home": "Oregon Utah Under",
    "ho": "UNOU",
    "visitor": "Oregon Utah Over",
    "vis": "OVOU",
    "favorite": 0,
    "line": "59.5",
    "start": "12/4/2021 1:00:00 AM",
    "note": "",
    "winner": "0",
    "priority": 0
  },
  {
    "game": 13,
    "home": "Baylor OKST Under",
    "ho": "UNBO",
    "visitor": "Baylor OKST Over",
    "vis": "OVBO",
    "favorite": 0,
    "line": "47.5",
    "start": "12/4/2021 5:00:00 PM",
    "note": "",
    "winner": "0",
    "priority": 0
  },
  {
    "game": 14,
    "home": "Cin Hou Under",
    "ho": "UNCH",
    "visitor": "Cin Hou Over",
    "vis": "OVCH",
    "favorite": 0,
    "line": "54.5",
    "start": "12/4/2021 5:00:00 PM",
    "note": "",
    "winner": "0",
    "priority": 0
  },
  {
    "game": 15,
    "home": "Bama UGA Under",
    "ho": "UNAG",
    "visitor": "Bama UGA Over",
    "vis": "OVAG",
    "favorite": 0,
    "line": "50.5",
    "start": "12/4/2021 5:00:00 PM",
    "note": "",
    "winner": "0",
    "priority": 0
  },
  {
    "game": 16,
    "home": "Pitts Wake Under",
    "ho": "UNPW",
    "visitor": "Pitt Wake Over",
    "vis": "OVPW",
    "favorite": 0,
    "line": "72.5",
    "start": "12/4/2021 5:00:00 PM",
    "note": "",
    "winner": "0",
    "priority": 0
  },
  {
    "game": 17,
    "home": "Iowa Mich Under",
    "ho": "UNIM",
    "visitor": "Iowa Mich Over",
    "vis": "OVIM",
    "favorite": 0,
    "line": "43.5",
    "start": "12/4/2021 5:00:00 PM",
    "note": "",
    "winner": "0",
    "priority": 0
  },
  {
    "game": 18,
    "home": "USC Cal Under",
    "ho": "UNUC",
    "visitor": "USC Cal Over",
    "vis": "OVUC",
    "favorite": 0,
    "line": "57.5",
    "start": "12/4/2021 5:00:00 PM",
    "note": "",
    "winner": "0",
    "priority": 0
  },
  {
    "game": 19,
    "home": "Kansas City",
    "ho": "KC",
    "visitor": "Denver",
    "vis": "DEN",
    "favorite": 1,
    "line": "10.5",
    "start": "12/4/2021 5:00:00 PM",
    "note": "",
    "winner": "0",
    "priority": 0
  },
  {
    "game": 20,
    "home": "Buffalo",
    "ho": "BUF",
    "visitor": "New England",
    "vis": "NE",
    "favorite": 1,
    "line": "3.5",
    "start": "12/4/2021 5:00:00 PM",
    "note": "",
    "winner": "0",
    "priority": 0
  }
]

const convertedBowlGames = [
  {
    "week": 16,
    "game": 1,
    "vis": "CMIC",
    "visitor": "Central Michigan",
    "ho": "SDST",
    "home": "San Diego State",
    "favorite": 1,
    "line": 3.5,
    "winner": 0,
    "note": "New Mexico Bowl",
    "priority": 1,
    "start": "12/21/2021 12:00:00 PM"
  },
  {
    "week": 16,
    "game": 2,
    "vis": "BSU",
    "visitor": "Bosie State",
    "ho": "UW",
    "home": "Washington",
    "favorite": 1,
    "line": 3.5,
    "winner": 0,
    "note": "Las Vegas Bowl",
    "priority": 1,
    "start": "12/21/2021 5:30:00 PM"
  },
  {
    "week": 16,
    "game": 3,
    "vis": "BYU",
    "visitor": "Brigham Young",
    "ho": "HAW",
    "home": "Hawaii",
    "favorite": 0,
    "line": 2.5,
    "winner": 0,
    "note": "Hawaii Bowl",
    "priority": 1,
    "start": "12/24/2021 6:00:00 PM"
  },
  {
    "week": 16,
    "game": 4,
    "vis": "LT",
    "visitor": "Louisiana Tech",
    "ho": "MIA",
    "home": "Miami",
    "favorite": 1,
    "line": 6.5,
    "winner": 0,
    "note": "Independence Bowl",
    "priority": 1,
    "start": "12/26/2021 2:00:00 PM"
  },
  {
    "week": 16,
    "game": 5,
    "vis": "EMIC",
    "visitor": "Eastern Michigan",
    "ho": "PITT",
    "home": "Pittsburgh",
    "favorite": 1,
    "line": 11.5,
    "winner": 0,
    "note": "Quick Lane Bowl",
    "priority": 1,
    "start": "12/26/2021 6:00:00 PM"
  },
  {
    "week": 16,
    "game": 6,
    "vis": "NC",
    "visitor": "North Carolina",
    "ho": "TEM",
    "home": "Temple",
    "favorite": 0,
    "line": 4.5,
    "winner": 0,
    "note": "Military Bowl",
    "priority": 1,
    "start": "12/27/2021 10:00:00 AM"
  },
  {
    "week": 16,
    "game": 7,
    "vis": "LOU",
    "visitor": "Louisville",
    "ho": "MSST",
    "home": "Mississippi State",
    "favorite": 1,
    "line": 4.5,
    "winner": 0,
    "note": "Music City Bowl",
    "priority": 1,
    "start": "12/30/2021 2:00:00 PM"
  },
  {
    "week": 16,
    "game": 8,
    "vis": "CAL",
    "visitor": "California",
    "ho": "ILL",
    "home": "Illinois",
    "favorite": 0,
    "line": 7.5,
    "winner": 0,
    "note": "Red Box Bowl",
    "priority": 1,
    "start": "12/30/2021 2:00:00 PM"
  },
  {
    "week": 16,
    "game": 9,
    "vis": "UK",
    "visitor": "Kentucky",
    "ho": "VT",
    "home": "Virginia Tech",
    "favorite": 1,
    "line": 3.5,
    "winner": 0,
    "note": "Belk Bowl",
    "priority": 1,
    "start": "12/31/2021 10:00:00 AM"
  },
  {
    "week": 16,
    "game": 10,
    "vis": "IN",
    "visitor": "Indiana",
    "ho": "TN",
    "home": "Tennessee",
    "favorite": 1,
    "line": 1.5,
    "winner": 0,
    "note": "Gator Bowl",
    "priority": 1,
    "start": "1/2/2022 5:00:00 PM"
  },
  {
    "week": 16,
    "game": 11,
    "vis": "MSU",
    "visitor": "Michigan State",
    "ho": "WF",
    "home": "Wake Forest",
    "favorite": 0,
    "line": 4.5,
    "winner": 0,
    "note": "Pin Stripe Bowl",
    "priority": 2,
    "start": "12/27/2021 1:20:00 PM"
  },
  {
    "week": 16,
    "game": 12,
    "vis": "OKST",
    "visitor": "Oklahoma State",
    "ho": "A&M",
    "home": "Texas A&M",
    "favorite": 1,
    "line": 7.5,
    "winner": 0,
    "note": "Texas Bowl",
    "priority": 2,
    "start": "12/27/2021 4:45:00 PM"
  },
  {
    "week": 16,
    "game": 13,
    "vis": "IOWA",
    "visitor": "Iowa",
    "ho": "USC",
    "home": "Southern California",
    "favorite": 0,
    "line": 2.5,
    "winner": 0,
    "note": "Holiday Bowl",
    "priority": 2,
    "start": "12/27/2021 6:00:00 PM"
  },
  {
    "week": 16,
    "game": 14,
    "vis": "AF",
    "visitor": "Air Force",
    "ho": "WSU",
    "home": "Washington State",
    "favorite": 0,
    "line": 3.5,
    "winner": 0,
    "note": "Cheeze-it Bowl",
    "priority": 2,
    "start": "12/27/2021 8:15:00 PM"
  },
  {
    "week": 16,
    "game": 15,
    "vis": "ISU",
    "visitor": "Iowa State",
    "ho": "ND",
    "home": "Notre Dame",
    "favorite": 1,
    "line": 3.5,
    "winner": 0,
    "note": "Camping World Bowl",
    "priority": 2,
    "start": "12/28/2021 10:00:00 AM"
  },
  {
    "week": 16,
    "game": 16,
    "vis": "UF",
    "visitor": "Florida",
    "ho": "UVA",
    "home": "Virginia",
    "favorite": 0,
    "line": 14.5,
    "winner": 0,
    "note": "Orange Bowl",
    "priority": 2,
    "start": "12/30/2021 6:00:00 PM"
  },
  {
    "week": 16,
    "game": 17,
    "vis": "ASU",
    "visitor": "Arizona State",
    "ho": "FSU",
    "home": "Florida Sate",
    "favorite": 0,
    "line": 4.5,
    "winner": 0,
    "note": "Sun Bowl",
    "priority": 2,
    "start": "12/31/2021 12:00:00 PM"
  },
  {
    "week": 16,
    "game": 18,
    "vis": "KSU",
    "visitor": "Kansas State",
    "ho": "NAVY",
    "home": "Navy",
    "favorite": 1,
    "line": 2.5,
    "winner": 0,
    "note": "Liberty Bowl",
    "priority": 2,
    "start": "12/31/2021 1:45:00 PM"
  },
  {
    "week": 16,
    "game": 19,
    "vis": "UT",
    "visitor": "Texas",
    "ho": "UTAH",
    "home": "Utah",
    "favorite": 1,
    "line": 7.5,
    "winner": 0,
    "note": "Alamo Bowl",
    "priority": 2,
    "start": "12/31/2021 5:30:00 PM"
  },
  {
    "week": 16,
    "game": 20,
    "vis": "AUB",
    "visitor": "Auburn",
    "ho": "MN",
    "home": "Minnesota",
    "favorite": 0,
    "line": 7.5,
    "winner": 0,
    "note": "Outback Bowl",
    "priority": 2,
    "start": "1/1/2022 10:00:00 AM"
  },
  {
    "week": 16,
    "game": 21,
    "vis": "MEM",
    "visitor": "Memphis",
    "ho": "PSU",
    "home": "Penn State",
    "favorite": 1,
    "line": 6.5,
    "winner": 0,
    "note": "Cotton Bowl",
    "priority": 3,
    "start": "12/28/2021 10:00:00 AM"
  },
  {
    "week": 16,
    "game": 22,
    "vis": "BAMA",
    "visitor": "Alabama",
    "ho": "MICH",
    "home": "Michigan",
    "favorite": 0,
    "line": 7.5,
    "winner": 0,
    "note": "Citrus Bowl",
    "priority": 3,
    "start": "1/1/2022 11:00:00 AM"
  },
  {
    "week": 16,
    "game": 23,
    "vis": "ORE",
    "visitor": "Oregon",
    "ho": "WIS",
    "home": "Wisconsin",
    "favorite": 1,
    "line": 2.5,
    "winner": 0,
    "note": "Rose Bowl",
    "priority": 3,
    "start": "1/1/2022 3:00:00 PM"
  },
  {
    "week": 16,
    "game": 24,
    "vis": "BU",
    "visitor": "Baylor",
    "ho": "UGA",
    "home": "Georgia",
    "favorite": 1,
    "line": 7.5,
    "winner": 0,
    "note": "Sugar Bowl",
    "priority": 3,
    "start": "1/1/2022 6:45:00 PM"
  },
  {
    "week": 16,
    "game": 25,
    "vis": "LSU",
    "visitor": "Louisianna State",
    "ho": "OU",
    "home": "Oklahoma",
    "favorite": 0,
    "line": 13.5,
    "winner": 0,
    "note": "Peach Bowl",
    "priority": 4,
    "start": "12/28/2021 2:00:00 PM"
  },
  {
    "week": 16,
    "game": 26,
    "vis": "CLEM",
    "visitor": "Clemson",
    "ho": "OSU",
    "home": "Ohio State",
    "favorite": 0,
    "line": 2.5,
    "winner": 0,
    "note": "Fiesta Bowl",
    "priority": 4,
    "start": "12/28/2021 6:00:00 PM"
  },
  {
    "week": 16,
    "game": 27,
    "vis": "CLEM",
    "visitor": "Clemson",
    "ho": "LSU",
    "home": "Louisiana St",
    "favorite": 1,
    "line": 6.5,
    "winner": 0,
    "note": "National Championship",
    "priority": 5,
    "start": "1/13/2022 6:00:00 PM"
  }
];